version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./rails/Dockerfile
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    volumes:
      - ./rails:/app
    ports:
      - "80:80"
      - "443:443"